- name: Install apt-transport-https
  apt: name=apt-transport-https state=installed

- name: Set sources.list (https)
  shell: /bin/echo "deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.2 main" > /etc/apt/sources.list.d/mongodb-org-3.2.list

- name: Get repo key
  shell: /usr/bin/apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927

- name: Update packages list
  apt: update_cache=yes

- name: Install Mongo packages (apt)
  apt: name=mongodb-org state=installed
